language:
  - python
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.0 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      script:
        - set -e  # If any of the following steps fail, just stop at that point.
        - make -C docs html  # Build the documentation.
        - pip3 install doctr
        - doctr deploy --built-docs docs/build/html .  # Publish the documentation.
    - name: "Python 3.6.0 on Xenial Linux"
      python: 3.6           # this works for Linux but is ignored on macOS or Windows
      # https://blog.travis-ci.com/2018-10-11-windows-early-release
    - name: "Python 3.7.5 on macOS, xcode11.2"
      os: osx
      osx_image: xcode11.2  # Python 3.7.5 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      # python: 3.7         # 'python:' is ignored on Travis CI macOS
      before_install:
        python3 --version ; pip3 --version ; sw_vers
    - name: "Python 3.7.5 on macOS, xcode10"
      os: osx
      osx_image: xcode10  # Python 3.7.4 running on macOS 10.13.6
      language: shell       # 'language: python' is an error on Travis CI macOS
      # python: 3.7         # 'python:' is ignored on Travis CI macOS
      before_install:
        python3 --version ; pip3 --version ; sw_vers
    - name: "Python 3.7.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      # python: 3.7         # 'python:' is ignored on Travis CI Windows
      before_install:
        - choco install python --version 3.7.4
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
        - pip3 install codecov
        - pip3 install opencv-python-headless
        - pip3 install opencv-contrib-python-headless
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      # python: 3.7         # 'python:' is ignored on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
        - pip3 install opencv-python-headless
        - pip3 install opencv-contrib-python-headless
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

install:
  # Install this package and the packages listed in requirements.txt.
  - pip3 install --upgrade pip
  - pip3 install . #pip install --upgrade pip
  # Install extra requirements for running tests and building docs.
  - pip3 install -r requirements-dev.txt

script:
  - coverage run -m pytest  # Run the tests and check for test coverage.
  - coverage report -m  # Generate test coverage report.
  - codecov  # Upload the report to codecov.
  #turn flake8 on when all formating issues are fixed and understood.
  # - flake8  # Enforce code style ('relaxed' line length limit is set in .flake8 config file).

notifications:
  email: false
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

env:
  global:
    # Doctr deploy key for vstadnytskyi/circular_buffer_numpy
    - secure: "UAaRorqCCSxP3P2mJ6gMLVYrxw/TBUGVwOIHNGcS1F00Sn0E/2cvhjrBriYZgoGn57/M/NQev6jJGqy5p6qaM0TDuIXifAsVaq7bsJcFh4Gfv7CAqoQVoY4vOXvoXL9nvjD6Sg4/P+ZNO6aLFLLWBHj0wXggJ4lmxUf6PK2V09t
DJWNc/FH9yZKZCB2CTlxLriA+lIO/KCsNuNszphNt8ZQyzRb+MHWRrZS5rAriGr45jUCH0qFWyQmjG8rLrMWhwsPWwLZD3YivPPUgCSlt+qd+C5CN6Bqh39NvJXREre2uKyXel+FUpvmI1PtWWmtvbMEPfsRZoXHfs30NAFPTe/m/Ux1fZJ7Z4pOIxSHLc
4QlIYhcsVKkoISZwiBktBnHaSVQBi5VmXayetTnLp6wkUV7Fzird4/1DrWfWpiq0gwR1xbvCof/O8SDeKMzp2AOib7AMI+CieExakkEclx6ZreUW4e64TG++iwc9F6ByApmGXMI0yAs9Opt0jKx7BCNT/2oe6KDTG1cpNKLELfsh/ySyUsngL1lHq9x9TV
a+JQLt0mKUruCWrVtdng3G+1Hex+gAZWfnFtMcysC6kGnVn+zKUqhVDjUyRZr61qra1oCOg7WFse39igEwdGxBqeEREEBKSa3Uk9n0wsFFjMBCgvNBTDoCnWsORjAhJfjlQI="
